### ISSUE TITLE
gUiADE frequently creates empty wav files when rendering to wav

### ISSUE THREAD

**Issue by sunshinespecialist** [Speedvicio/gUiADE#3]
Title.

**Comment by Speedvicio** [comment]
i can't reproduce your issue.
Can you attach a file that create this bug?

**Comment by sunshinespecialist** [comment]
https://files.exotica.org.uk/modland/?file=pub/modules/AHX/Jerry/maybe%20tomorrow.ahx
Frequently renders empty wav files when --frequency=96000 is in the settings.

**Comment by Speedvicio** [comment]
@etoubleh 

Tested on my pc with this setting:

![image](https://user-images.githubusercontent.com/13048199/226275929-d8eacf14-1d32-4c79-bd0f-a86b0bb8be27.png)

Normal export

![image](https://user-images.githubusercontent.com/13048199/226277894-1ed101a4-26c1-4739-9948-6c338c8d9146.png)

Quad export without post-processing

![image](https://user-images.githubusercontent.com/13048199/226278769-78bc4a98-63df-437e-ad9f-13081c5fd99c.png)


Exported in normal wav and quad wav and it work

**Comment by Speedvicio** [comment]
> https://files.exotica.org.uk/modland/?file=pub/modules/AHX/Jerry/maybe%20tomorrow.ahx Frequently renders empty wav files when --frequency=96000 is in the settings.

Can you see if this release solve your problem?

https://github.com/Speedvicio/gUiADE/releases/tag/0.6

**Comment by sunshinespecialist** [comment]
Yes, it works now.
